export const dogbreeds = [
  { id: 1, name: "Affenpinscher" },
  { id: 2, name: "Aidi" },
  { id: 3, name: "Alano Español" },
  { id: 4, name: "Airedale Terrier" },
  { id: 5, name: "Akita Inu" },
  { id: 6, name: "Akita Americano" },
  { id: 7, name: "American Bully" },
  { id: 8, name: "Alaskan Malamute" },
  { id: 9, name: "Alaskan Klee Kai" },
  { id: 10, name: "American Pit Bull Terrier" },
  { id: 11, name: "American Staffordshire" },
  { id: 12, name: "Australian Silky Terrier" },
  { id: 13, name: "Azawakh" },
  { id: 14, name: "Basenji" },
  { id: 15, name: "Barbet" },
  { id: 16, name: "Basset Alpino" },
  { id: 17, name: "Basset Artesiano de Normandia" },
  { id: 18, name: "Basser Azul de Gascuña" },
  { id: 19, name: "Basset Leonado de Bretaña" },
  { id: 20, name: "Basset Hound" },
  { id: 21, name: "Beagle" },
  { id: 22, name: "Beagle-Harrier" },
  { id: 23, name: "Beauceron" },
  { id: 24, name: "Bedlington Terrier" },
  { id: 25, name: "Bergamasco" },
  { id: 26, name: "Bolognese" },
  { id: 27, name: "Bichon de pelo Frisado" },
  { id: 28, name: "Bichon Habanero" },
  { id: 29, name: "Bloodhound" },
  { id: 30, name: "Bobtail" },
  { id: 31, name: "Boyero de Appenzell" },
  { id: 32, name: "Border Collie" },
  { id: 33, name: "Bóxer" },
  { id: 34, name: "Boston Terrier" },
  { id: 35, name: "Borzoi" },
  { id: 36, name: "Boyero de Berna" },
  { id: 37, name: "Boyero de Flandes" },
  { id: 38, name: "Braco Aleman de Pelo Corto" },
  { id: 39, name: "Braco Frances" },
  { id: 40, name: "Buhund Noruego" },
  { id: 41, name: "Bullmastiff" },
  { id: 42, name: "Bull Terrier" },
  { id: 43, name: "Bulldog Francés" },
  { id: 44, name: "Bulldog Inglés" },
  { id: 45, name: "Cao de Agua Portugues" },
  { id: 46, name: "Cao de Castro Laboreiro" },
  { id: 47, name: "Cao de Fila de Sao Miguel" },
  { id: 48, name: "Cao de Serra de Aires" },
  { id: 49, name: "Cao de Serra de Estrella" },
  { id: 50, name: "Cardigan Welsh Corgi" },
  { id: 51, name: "Cavalier King Charles Spaniel" },
  { id: 52, name: "Cazador de alces Noruego" },
  { id: 53, name: "Cesky Terrier" },
  { id: 54, name: "Cimarron Uruguayo" },
  { id: 55, name: "Chesapeake Bay Terrier" },
  { id: 56, name: "Chihuahua" },
  { id: 57, name: "Chin Japones" },
  { id: 58, name: "Chow Chow" },
  { id: 59, name: "Cirneco del Etna" },
  { id: 60, name: "Clumber Spaniel" },
  { id: 61, name: "Cobrador de Pelo Liso" },
  { id: 62, name: "Cocker Spaniel" },
  { id: 63, name: "Cocher Spaniel Americano" },
  { id: 64, name: "Collie" },
  { id: 65, name: "Collie de pelo corto" },
  { id: 66, name: "Crestado Chino" },
  { id: 67, name: "Dandie Dinmont Terrier" },
  { id: 68, name: "Dálmata" },
  { id: 69, name: "Doberman" },
  { id: 70, name: "Dogo Aleman" },
  { id: 71, name: "Dogo Argentino" },
  { id: 72, name: "Dogue des Bordeaux" },
  { id: 73, name: "East Siberian Laika" },
  { id: 74, name: "Entlebucher" },
  { id: 75, name: "Eurasier" },
  { id: 76, name: "Eupagneul Breton" },
  { id: 77, name: "Fila Brasileño" },
  { id: 78, name: "Field Spaniel" },
  { id: 79, name: "Fox Terrier" },
  { id: 80, name: "Foxhound Americano" },
  { id: 81, name: "Galgo Hungaro" },
  { id: 82, name: "Galgo Ingles" },
  { id: 83, name: "Galgo Italiano" },
  { id: 84, name: "Gleen of imaall Terrier" },
  { id: 85, name: "Golden Retriever" },
  { id: 86, name: "Gran Danés" },
  { id: 87, name: "Greyhound" },
  { id: 88, name: "Grifon Belga" },
  { id: 89, name: "Hovawart" },
  { id: 90, name: "Huskey Siberiano" },
  { id: 91, name: "Jack Russell Terrier" },
  { id: 92, name: "Keshoond" },
  { id: 93, name: "Kerry Blue Terrier" },
  { id: 94, name: "Komondor" },
  { id: 95, name: "Kuvasz" },
  { id: 96, name: "Labrador Retriever" },
  { id: 97, name: "Lebrel Afgano" },
  { id: 98, name: "Lebrel Escoses" },
  { id: 99, name: "Lebrel Polaco" },
  { id: 100, name: "Leonberger" },
  { id: 101, name: "Lobero Irlandes" },
  { id: 102, name: "Lobo de Saarlos" },
  { id: 103, name: "Lowchen" },
  { id: 104, name: "Lundehund" },
  { id: 105, name: "Manchester Terrier" },
  { id: 106, name: "Maltese" },
  { id: 107, name: "Mastin Español" },
  { id: 108, name: "Mastín Napolitano" },
  { id: 109, name: "Mastín Tibetano" },
  { id: 110, name: "Mastín del Pireneo" },
  { id: 111, name: "Mudi" },
  { id: 112, name: "Mucuchies" },
  { id: 113, name: "Munsterlander Grande" },
  { id: 114, name: "Munsterlader pequeño" },
  { id: 115, name: "Norfolk Terrier" },
  { id: 116, name: "Norwegian Elkhound" },
  { id: 117, name: "Nova Scotia Duck Tolling Retriever" },
  { id: 118, name: "Otterhound" },
  { id: 119, name: "Pachon Navarro" },
  { id: 120, name: "Phalene" },
  { id: 121, name: "Papillon" },
  { id: 122, name: "Pastor Alemán" },
  { id: 123, name: "Pastor Croata" },
  { id: 124, name: "Pastor de Brie" },
  { id: 125, name: "Pastor Garafiano" },
  { id: 126, name: "Pastor Holandes" },
  { id: 127, name: "Pastor Leones" },
  { id: 128, name: "Pastor ovejero Australiano" },
  { id: 129, name: "Pastor Mallorquin" },
  { id: 130, name: "Pastor Maremanno Abruces" },
  { id: 131, name: "Pastor de Picardia" },
  { id: 132, name: "Pastor Peruano Chiribaya" },
  { id: 133, name: "Pastor Suizo" },
  { id: 134, name: "Pastor Vasco" },
  { id: 135, name: "Pastor de Valee" },
  { id: 136, name: "Pequinés" },
  { id: 137, name: "Perdiguero Frances" },
  { id: 138, name: "Perdiguero Portugues" },
  { id: 139, name: "Perro de Aguas Español" },
  { id: 140, name: "Perro de Artois" },
  { id: 141, name: "Perro de Groenlandia" },
  { id: 142, name: "Perro Dogo Mallorquin" },
  { id: 143, name: "Perro Bodeguero" },
  { id: 144, name: "Perro Esquimal Canadiense" },
  { id: 145, name: "Perro Fino Colombiano" },
  { id: 146, name: "Perro Majorero" },
  { id: 147, name: "Perro de montaña de los Pirineos" },
  { id: 148, name: "Perro Lobo Checoslovacco" },
  { id: 149, name: "Perro Ovejero Megallanico" },
  { id: 150, name: "Perro Salchicha" },
  { id: 151, name: "Perro Pastor de las islas de Shetland" },
  { id: 152, name: "Perro Presa Canario" },
  { id: 153, name: "Perro Podenco" },
  { id: 154, name: "Perro Podenco Canario" },
  { id: 155, name: "Perro Podenco Ibicenco" },
  { id: 156, name: "Perro Podenco Portugues" },
  { id: 157, name: "Perro Pumi" },
  { id: 158, name: "Pinscher Miniatura" },
  { id: 159, name: "Pointer Ingles" },
  { id: 160, name: "Pomsky" },
  { id: 161, name: "Pomerania" },
  { id: 162, name: "Poodle" },
  { id: 163, name: "Pug" },
  { id: 164, name: "Puli" },
  { id: 165, name: "Pudelpointer" },
  { id: 166, name: "Rafeiro do Alentejo" },
  { id: 167, name: "Ratonero Valenciano" },
  { id: 168, name: "Ridgeback Tailandes" },
  { id: 169, name: "Rhodesian Ridgeback" },
  { id: 170, name: "Rottweiler" },
  { id: 171, name: "Sabueso Bosnio" },
  { id: 172, name: "Samoyedo" },
  { id: 173, name: "San Bernardo" },
  { id: 174, name: "Schnauzer" },
  { id: 175, name: "Schapondoes" },
  { id: 176, name: "Schipperke" },
  { id: 177, name: "Setter Ingles" },
  { id: 178, name: "Setter Irlandes" },
  { id: 179, name: "Shar Pei" },
  { id: 180, name: "Shiba Inu" },
  { id: 181, name: "Shih Tzu" },
  { id: 182, name: "Shikoku Inu" },
  { id: 183, name: "Skye Terrier" },
  { id: 184, name: "Spaniel Tibetano" },
  { id: 185, name: "Spitz Finlandes" },
  { id: 186, name: "Spitz Japones" },
  { id: 187, name: "Spitz Enano" },
  { id: 188, name: "Spitz Mediano" },
  { id: 189, name: "Springer Spaniel Ingles" },
  { id: 190, name: "Staffordhire Bull Terrier" },
  { id: 191, name: "Sussex Spaniel" },
  { id: 192, name: "Teckel" },
  { id: 193, name: "Terranova" },
  { id: 194, name: "Terrier Aleman" },
  { id: 195, name: "Terrier Australiano" },
  { id: 196, name: "Terrier Brasileno" },
  { id: 197, name: "Terrier de Nordfolk" },
  { id: 198, name: "Terrier de Norwich" },
  { id: 199, name: "Terrier Checo" },
  { id: 200, name: "Terrier Chileno" },
  { id: 201, name: "Terrier Escoces" },
  { id: 202, name: "Terrier Gales" },
  { id: 203, name: "Terrier Irlandes" },
  { id: 204, name: "Terrier Ruso Negro" },
  { id: 205, name: "Terrier Tibetano" },
  { id: 206, name: "Tervueren" },
  { id: 207, name: "Toy Espaniel Ingles" },
  { id: 208, name: "Vallhund Seco" },
  { id: 209, name: "Volpino Italiano" },
  { id: 210, name: "Whippet" },
  { id: 211, name: "Weimaraner" },
  { id: 212, name: "West Higland white Terrier o Perro Westy" },
  { id: 213, name: "Wolfsspitz" },
  { id: 214, name: "Xoloitzcuintle" },
  { id: 215, name: "Yorkshire Terrier" }
]